# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Danielle Neve Koran
title: Senior Network System Administrator
email: daniell.neve.koran@gmail.com
website: thedivadanielle.github.com

# Social links
twitter_username: TheDivaDanielle
github_username: TheDivaDanielle
# dribbble_username: jekyll
facebook_username: webjediwife
# flickr_username: jekyll
instagram_username: thedivadanielle
linkedin_username: danielle-koran
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/avataaars.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Danielle and I'm a IT Manager and Technologist. I have worked at a number of companies gaining teamwork and leadership skills.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience
# experience_content: |


# Education Section
# educaton_title: Education


# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in technology some of my other interests and hobbies are:
   - Motorcycling
   - Guitars & Music
   - Video Games

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
